apiVersion: v1
kind: Service
metadata:
  name: {{ include "document-generator-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "document-generator-service.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9999
      protocol: TCP
      name: http
  selector:
    app: {{ include "document-generator-service.name" . }}
